# Generated by Django 3.1.7 on 2021-03-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('s', 'started'), ('a', 'active'), ('c', 'completed')], default='s', max_length=1)),
            ],
        ),
    ]
