# Generated by Django 3.1.7 on 2021-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='units',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
