# Generated by Django 3.1.7 on 2021-04-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210412_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='repository',
            field=models.URLField(blank=True),
        ),
    ]
