# Generated by Django 3.1.7 on 2021-04-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_learn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
