# Generated by Django 3.1.7 on 2021-04-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_resource_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
